version: '3.8'

services:
    app:
        container_name: angular-working-with-ssr-and-i18n

        build:
            context: .
            dockerfile: Dockerfile

        ports:
            - 4200:4200

        volumes:
            - ./app:/app

        command: /bin/sh -c "while sleep 1000; do :; done"

networks:
    default:
        name: angular-working-with-ssr-and-i18n_network